export type Client = {
  id: string;
  tenant_id: string;
  name: string;
  phone: string | null;
  phone2: string | null;
  email: string | null;
  vat: string | null;
  address: string | null;
  professional_status: string | null;
  notes: string | null;
  father_name: string | null;
  mother_name: string | null;
  birthdate: string | null;
  amka: string | null;
  iban: string | null;
  at: string | null;
  taxis_username: string | null;
  taxis_password: string | null;
  contact_id: string | null;
  created_at: string;
};

export type ClientFormData = {
  name: string;
  phone: string;
  phone2: string;
  email: string;
  vat: string;
  address: string;
  professional_status: string;
  notes: string;
  father_name: string;
  mother_name: string;
  birthdate: string;
  amka: string;
  iban: string;
  at: string;
  taxis_username: string;
  taxis_password: string;
};
